epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 3.e-4
num_layers: 4
svd_dim: 70
dropout_rate: 0.
embedding_dim: 64
hidden_dim: 256
stablegcn_lmbda: 1.5
stablegcn_alpha: 20.
stablegcn_upper: 0.5
stablegcn_lower: 0.2