epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-4
init_std: 0.1
keep_prob: 0.6
A_split: False
dropout: True
embedding_dim: 64
num_layers: 0
dropout_rate: 0.1
gtn_K: 3
gtn_alpha: 0.3
gtn_beta: 0.5
gtn_lambda2: 4.0