epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-8
init_std: 1.e-2
embedding_dim: 64
simplex_dropout_rate: 0.2
simplex_similarity_score: cosine
simplex_gamma: 0.6
simplex_margin: 0.1
simplex_max_len: 500
simplex_negative_weight: 2