epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-8
init_std: 0.1
keep_prob: 0.6
A_split: False
dropout: False
embedding_dim: 64
num_layers: 2
jgcf_alpha: 0.1
jgcf_jacobi_a: 2.0
jgcf_jacobi_b: 1.1
base_coeff: 3.0